In [ ]:
# Numpy advance  

In [ ]:
import numpy as np

# creating a 1-D array
a = np.array([1,2,3])
b = [4, 7, 8, 12]
print(type(a))
print(a.shape)
print(b)
print(type(b))
print(a[0], a[1], a[2])
a[0] = 5
print(a)

In [9]:
# creating a 2-D array
b = np.array([[1,2,3], [4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

[[7 7]
 [7 7]]


In [13]:
# whenever there is a null value or missing value in a dataset we need to fill the values with 
# 0, 1, mean, median or mode for data pre processing 
a = np.zeros((2,2))
print(a)
b = np.ones((1,2))
print(b)
c = np.full((2,2),7)
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]


In [15]:
d = np.eye(2)
print(d)
e= np.random.random((2,2))
print(e)

[[1. 0.]
 [0. 1.]]
[[0.86005723 0.35640469]
 [0.47082725 0.26734497]]


In [51]:
# numpy.random.randint(low, high=None, size=None, dtype=’l’)
e=np.random.randint(2,100,(5,1,3))
print(e)

# numpy.linspace(start, stop, num=50, endpoint=True , retstep=False, dtype=None, axis=0)
f = np.linspace(0, 2, 10)
print(f)

[[[81 31 85]]

 [[40 23 67]]

 [[25 61 87]]

 [[41 36 97]]

 [[59 79 35]]]


In [73]:
# slicing 

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0,1])
print(a[:,:])
print(a[:2, 1:3])
print(a[0:2, 1:2])
print(a[2:3, 0:2])
print(a[:2, 1:])
print(a[-2:-1, -2:-1])
print(a[-2:1, 1:-3])

2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[2]
 [6]]
[[ 9 10]]
[[2 3 4]
 [6 7 8]]
[[7]]
[]


In [83]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2], [0,1,0]])
print(np.array([a[0,0], a[1,1], a[2,0]]))
print(a[[0,0], [1,1]])
print(np.array([a[0,1], a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [87]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b = np.array([0,2,0,1])
print(a[np.arange(4), b])
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [93]:
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [101]:
x = np.array([[1,2],[3,4]], dtype= np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x/y)
print(np.divide(x,y))
print(x*y)
print(np.multiply(x,y))
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [103]:
x = np.array([[1,2],[3,4]])
print(x)
print(x.T)
v = np.array([1,2,3])
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]


In [105]:
arr = np.arange(16)
print("The Original Array is:\n",arr)
arr1 = np.arange(16).reshape(2,8)
print("The Reshaped array is:\n",arr1)

The Original Array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
The Reshaped array is:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [109]:
# eigen values Eigenvalues are the scalar values associated with the eigenvectors in linear transformation.
# eigen vectors Eigenvectors for square matrices are defined as non-zero vector values which when multiplied by the square matrices give the scaler multiple of the vector, i.e. we define an eigenvector for matrix A to be “v” if it specifies the condition, Av = λv

import numpy as np 
x = np.array([[1, 2], [2, 3]])  
print("Printing the Original square array:\n", x)   
# finding eigenvalues and eigenvectors 
y, z = np.linalg.eig(x) 

print("Printing the Eigen values of the given square array:\n", y)    # values
print("Printing Right eigenvectors of the given square array:\n", z)   # vectors 

Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
